### PR TITLE
fix: improve mastery level dropdown styling and validation

### LINKED ISSUE #75: [Bug] Mastery level displayed as "undefined" if none is chosen
You can add a skill to your profile without specifying the mastery level, and it ends up being set to undefined:

image

### PR DESCRIPTION
**Pull request by tawaks**
Fixes #75

### CODE REVIEW

**Comment by tawaks** [comment]
Hi @s1lvax 
I tried to add a zod schema error message that should have been displayed if one only submits a skill without a mastery level but it i could not make it work.
However I have made sure that we cannot have undefined as a mastery level option. 
I also made the UI for the dropdown better

**Comment by tawaks** [comment]
image

**Comment by tawaks** [comment]
I have noticed that someone has already added dropdown styling improvements , so the only important line that i should have committed is adding "required" to the input.

**Comment by s1lvax** [comment]
Thanks @tawaks ! I'm merging it :)

**Comment by tawaks** [comment]
Thanks @s1lvax

**Pull request merged**
