### PR TITLE
Display date as local time instead of utc+0 time

### LINKED ISSUE #28: [Bug] "Last Updated" card when editing profile shows UTC+0 time
For example, it currently shows 6:25, but if it is adjusted to my timezone it should be 8:25
image

### PR DESCRIPTION
**Pull request by Discusser**
Fixes #28

### CODE REVIEW

**Comment by s1lvax** [comment]
Your pull request #31 which I already merged seems to fix this.. when I try it this way it doesn't even seem to work (to me at least it shows 2 hours behind). 


Let me know if I'm missing something, if not then I'll close this one. Many thanks again !

**Comment by s1lvax** [comment]
This doesn't seem to work for me, at least locally.. To me it's still displaying the incorrect time.. Maybe I am missing something ? 

Could you please double check ? :D

**Comment by Discusser** [comment]
I believe the issue is solved now. It seems that this PR could've been included in #31 since the `toLocaleString` method of `Date` converts a date to a representation in the local timezone. Dates in JavaScript are always internally stored as UTC, which is why, normally, no conversions are needed unless you want to display the date.

**Comment by s1lvax** [comment]
Hi @Discusser , thank you so much for these changes for these are no longer needed.

Pls check PR #40

**Pull request closed without merging**
