### PR TITLE
[Feature] Add Hobbies (#55)

### LINKED ISSUE #55: [Feature] Add hobbies
This configuration would be optional, and it only gets shown on the Public Profile if at least 1 is defined.

#### Schema for the Hobby table

```ts
id: autoincrement
userId: references to the User's table
hobby: string
createdAt
```

### PR DESCRIPTION
**Pull request by tawaks**
Fixes #55
profile:
image

[Username]:
image

### CODE REVIEW

**Comment by tawaks** [comment]
[username]:
image

**Comment by tawaks** [comment]
[username]:


Screenshot from 2024-10-23 10-59-46

**Comment by tawaks** [comment]
Hi @s1lvax , Let me know if you are happy with this :)

**Comment by s1lvax** [comment]
Hi @tawaks , that's looks amazing. 

I have nothing to criticize whatsoever, amazing job. 

Thank you so much for this big contribution :)

**Comment by tawaks** [comment]
Thanks @s1lvax

**Comment by s1lvax** [comment]
If you want, you can join the dev community on Discord, we discuss further details there, you'd obviously be a great addition :) (you can find it in the README)

**Comment by tawaks** [comment]
Thanks, I will join the community

**Comment by tawaks** [comment]
Hi @s1lvax 
The Discord link does not work.
I tried it on my computer and mobile phone

**Pull request merged**
